/* Created by RJudd */
/* SPAWARSYSCEN D857 */
/**********************************************************************
// For TASP VSIPL Documentation and Code neither the United States    /
// Government, the United States Navy, nor any of their employees,    /
// makes any warranty, express or implied, including the warranties   /
// of merchantability and fitness for a particular purpose, or        /
// assumes any legal liability or responsibility for the accuracy,    /
// completeness, or usefulness of any information, apparatus,         /
// product, or process disclosed, or represents that its use would    /
// not infringe privately owned rights                                /
**********************************************************************/
/* $Id: test_sc.c,v 1.3 2000/04/14 12:47:23 judd Exp judd $ */
#include"test_sc.h"

int main(int argc, char* argv[]){
     vsip_init((void*)0);
     argv++;
     while(--argc >0){
        if(!strcmp(*argv,"cgemp_f")){ cgemp_f(); argv++; }
        else if(!strcmp(*argv,"cgems_f")){ cgems_f(); argv++; }
        else if(!strcmp(*argv,"cmprod_f")){ cmprod_f(); argv++; }
        else if(!strcmp(*argv,"cmprodh_f")){ cmprodh_f(); argv++; }
        else if(!strcmp(*argv,"cmprodj_f")){ cmprodj_f(); argv++; }
        else if(!strcmp(*argv,"cmprodt_f")){ cmprodt_f(); argv++; }
        else if(!strcmp(*argv,"cmtrans_f")){ cmtrans_f(); argv++; }
        else if(!strcmp(*argv,"cmherm_f")){ cmherm_f(); argv++; }
        else if(!strcmp(*argv,"cmvprod_f")){ cmvprod_f(); argv++; }
        else if(!strcmp(*argv,"crvsub_f")){ crvsub_f(); argv++; }
        else if(!strcmp(*argv,"csvmul_f")){ csvmul_f(); argv++; }
        else if(!strcmp(*argv,"cvam_f")){ cvam_f(); argv++; }
        else if(!strcmp(*argv,"cvexp_f")){ cvexp_f(); argv++; }
        else if(!strcmp(*argv,"cvfill_f")){ cvfill_f(); argv++; }
        else if(!strcmp(*argv,"cvgather_f")){ cvgather_f(); argv++; }
        else if(!strcmp(*argv,"cvjdot_f")){ cvjdot_f(); argv++; }
        else if(!strcmp(*argv,"cvjmul_f")){ cvjmul_f(); argv++; }
        else if(!strcmp(*argv,"cvmag_f")){ cvmag_f(); argv++; }
        else if(!strcmp(*argv,"vcmagsq_f")){ vcmagsq_f(); argv++; }
        else if(!strcmp(*argv,"cvmeansqval_f")){ cvmeansqval_f(); argv++; }
        else if(!strcmp(*argv,"vmaxval_f")){ vmaxval_f(); argv++; }
        else if(!strcmp(*argv,"vminval_f")){ vminval_f(); argv++; }
        else if(!strcmp(*argv,"vsumsqval_f")){ vsumsqval_f(); argv++; }
        else if(!strcmp(*argv,"cvmmul_f")){ cvmmul_f(); argv++; }
        else if(!strcmp(*argv,"rvcmmul_f")){ rvcmmul_f(); argv++; }
        else if(!strcmp(*argv,"cvmprod_f")){ cvmprod_f(); argv++; }
        else if(!strcmp(*argv,"cvmsa_f")){ cvmsa_f(); argv++; }
        else if(!strcmp(*argv,"cvneg_f")){ cvneg_f(); argv++; }
        else if(!strcmp(*argv,"cvouter_f")){ cvouter_f(); argv++; }
        else if(!strcmp(*argv,"cvsam_f")){ cvsam_f(); argv++; }
        else if(!strcmp(*argv,"cvsma_f")){ cvsma_f(); argv++; }
        else if(!strcmp(*argv,"cvswap_f")){ cvswap_f(); argv++; }
        else if(!strcmp(*argv,"gemp_f")){ gemp_f(); argv++; }
        else if(!strcmp(*argv,"gems_f")){ gems_f(); argv++; }
        else if(!strcmp(*argv,"mprod_f")){ mprod_f(); argv++; }
        else if(!strcmp(*argv,"mprodt_f")){ mprodt_f(); argv++; }
        else if(!strcmp(*argv,"mtrans_f")){ mtrans_f(); argv++; }
        else if(!strcmp(*argv,"mvprod_f")){ mvprod_f(); argv++; }
        else if(!strcmp(*argv,"rcvadd_f")){ rcvadd_f(); argv++; }
        else if(!strcmp(*argv,"rcvmul_f")){ rcvmul_f(); argv++; }
        else if(!strcmp(*argv,"rscvmul_f")){ rscvmul_f(); argv++; }
        else if(!strcmp(*argv,"rcvsub_f")){ rcvsub_f(); argv++; }
        else if(!strcmp(*argv,"rscvadd_f")){ rscvadd_f(); argv++; }
        else if(!strcmp(*argv,"svadd_f")){ svadd_f(); argv++; }
        else if(!strcmp(*argv,"svdiv_f")){ svdiv_f(); argv++; }
        else if(!strcmp(*argv,"svmul_f")){ svmul_f(); argv++; }
        else if(!strcmp(*argv,"vadd_f")){ vadd_f(); argv++; }
        else if(!strcmp(*argv,"vsq_f")){ vsq_f(); argv++; }
        else if(!strcmp(*argv,"vsqrt_f")){ vsqrt_f(); argv++; }
        else if(!strcmp(*argv,"cvsqrt_f")){ cvsqrt_f(); argv++; }
        else if(!strcmp(*argv,"valltrue_bl")){ valltrue_bl(); argv++; }
        else if(!strcmp(*argv,"vam_f")){ vam_f(); argv++; }
        else if(!strcmp(*argv,"vanytrue_bl")){ vanytrue_bl(); argv++; }
        else if(!strcmp(*argv,"vasin_f")){ vasin_f(); argv++; }
        else if(!strcmp(*argv,"vacos_f")){ vacos_f(); argv++; }
        else if(!strcmp(*argv,"vatan2_f")){ vatan2_f(); argv++; }
        else if(!strcmp(*argv,"vatan_f")){ vatan_f(); argv++; }
        else if(!strcmp(*argv,"vclip_f")){ vclip_f(); argv++; }
        else if(!strcmp(*argv,"vcmaxmgsq_f")){ vcmaxmgsq_f(); argv++; }
        else if(!strcmp(*argv,"vcminmgsqval_f")){ vcminmgsqval_f(); argv++; }
        else if(!strcmp(*argv,"vcmplx_f")){ vcmplx_f(); argv++; }
        else if(!strcmp(*argv,"vdiv_f")){ vdiv_f(); argv++; }
        else if(!strcmp(*argv,"vdot_f")){ vdot_f(); argv++; }
        else if(!strcmp(*argv,"cvdot_f")){ cvdot_f(); argv++; }
        else if(!strcmp(*argv,"veuler_f")){ veuler_f(); argv++; }
        else if(!strcmp(*argv,"vexp_f")){ vexp_f(); argv++; }
        else if(!strcmp(*argv,"vexpoavg_f")){ vexpoavg_f(); argv++; }
        else if(!strcmp(*argv,"cvexpoavg_f")){ cvexpoavg_f(); argv++; }
        else if(!strcmp(*argv,"vfill_f")){ vfill_f(); argv++; }
        else if(!strcmp(*argv,"vgather_f")){ vgather_f(); argv++; }
        else if(!strcmp(*argv,"vhisto_f")){ vhisto_f(); argv++; }
        else if(!strcmp(*argv,"vhypot_f")){ vhypot_f(); argv++; }
        else if(!strcmp(*argv,"vinvclip_f")){ vinvclip_f(); argv++; }
        else if(!strcmp(*argv,"vleq_f")){ vleq_f(); argv++; }
        else if(!strcmp(*argv,"vlne_f")){ vlne_f(); argv++; }
        else if(!strcmp(*argv,"vlgt_f")){ vlgt_f(); argv++; }
        else if(!strcmp(*argv,"vlge_f")){ vlge_f(); argv++; }
        else if(!strcmp(*argv,"vllt_f")){ vllt_f(); argv++; }
        else if(!strcmp(*argv,"vlle_f")){ vlle_f(); argv++; }
        else if(!strcmp(*argv,"vlog_f")){ vlog_f(); argv++; }
        else if(!strcmp(*argv,"vlog10_f")){ vlog10_f(); argv++; }
        else if(!strcmp(*argv,"vmag_f")){ vmag_f(); argv++; }
        else if(!strcmp(*argv,"vmax_f")){ vmax_f(); argv++; }
        else if(!strcmp(*argv,"vmaxmg_f")){ vmaxmg_f(); argv++; }
        else if(!strcmp(*argv,"vmeansqval_f")){ vmeansqval_f(); argv++; }
        else if(!strcmp(*argv,"vmin_f")){ vmin_f(); argv++; }
        else if(!strcmp(*argv,"vminmg_f")){ vminmg_f(); argv++; }
        else if(!strcmp(*argv,"vmmul_f")){ vmmul_f(); argv++; }
        else if(!strcmp(*argv,"vmodulate_f")){ vmodulate_f(); argv++; }
        else if(!strcmp(*argv,"cvmodulate_f")){ cvmodulate_f(); argv++; }
        else if(!strcmp(*argv,"vmprod_f")){ vmprod_f(); argv++; }
        else if(!strcmp(*argv,"vmsa_f")){ vmsa_f(); argv++; }
        else if(!strcmp(*argv,"vnot_bl")){ vnot_bl(); argv++; }
        else if(!strcmp(*argv,"vouter_f")){ vouter_f(); argv++; }
        else if(!strcmp(*argv,"vpolar_f")){ vpolar_f(); argv++; }
        else if(!strcmp(*argv,"vrect_f")){ vrect_f(); argv++; }
        else if(!strcmp(*argv,"vramp_f")){ vramp_f(); argv++; }
        else if(!strcmp(*argv,"vreal_f")){ vreal_f(); argv++; }
        else if(!strcmp(*argv,"vimag_f")){ vimag_f(); argv++; }
        else if(!strcmp(*argv,"vrecip_f")){ vrecip_f(); argv++; }
        else if(!strcmp(*argv,"vsam_f")){ vsam_f(); argv++; }
        else if(!strcmp(*argv,"vscatter_f")){ vscatter_f(); argv++; }
        else if(!strcmp(*argv,"cvscatter_f")){ cvscatter_f(); argv++; }
        else if(!strcmp(*argv,"vsin_f")){ vsin_f(); argv++; }
        else if(!strcmp(*argv,"vcos_f")){ vcos_f(); argv++; }
        else if(!strcmp(*argv,"vsma_f")){ vsma_f(); argv++; }
        else if(!strcmp(*argv,"vsub_f")){ vsub_f(); argv++; }
        else if(!strcmp(*argv,"vsumval_f")){ vsumval_f(); argv++; }
        else if(!strcmp(*argv,"vsumval_bl")){ vsumval_bl(); argv++; }
        else if(!strcmp(*argv,"vtan_f")){ vtan_f(); argv++; }
        else if(!strcmp(*argv,"vneg_f")){ vneg_f(); argv++; }
        else if(!strcmp(*argv,"vmul_f")){ vmul_f(); argv++; }
        else if(!strcmp(*argv,"cvmul_f")){ cvmul_f(); argv++; }
        else if(!strcmp(*argv,"cvdiv_f")){ cvdiv_f(); argv++; }
        else if(!strcmp(*argv,"cvadd_f")){ cvadd_f(); argv++; }
        else if(!strcmp(*argv,"cvsub_f")){ cvsub_f(); argv++; }
        else if(!strcmp(*argv,"csvadd_f")){ csvadd_f(); argv++; }
        else if(!strcmp(*argv,"cvconj_f")){ cvconj_f(); argv++; }
        else if(!strcmp(*argv,"cgemp_d")){ cgemp_d(); argv++; }
        else if(!strcmp(*argv,"cgems_d")){ cgems_d(); argv++; }
        else if(!strcmp(*argv,"cmprod_d")){ cmprod_d(); argv++; }
        else if(!strcmp(*argv,"cmprodh_d")){ cmprodh_d(); argv++; }
        else if(!strcmp(*argv,"cmprodj_d")){ cmprodj_d(); argv++; }
        else if(!strcmp(*argv,"cmprodt_d")){ cmprodt_d(); argv++; }
        else if(!strcmp(*argv,"cmtrans_d")){ cmtrans_d(); argv++; }
        else if(!strcmp(*argv,"cmherm_d")){ cmherm_d(); argv++; }
        else if(!strcmp(*argv,"cmvprod_d")){ cmvprod_d(); argv++; }
        else if(!strcmp(*argv,"crvsub_d")){ crvsub_d(); argv++; }
        else if(!strcmp(*argv,"csvmul_d")){ csvmul_d(); argv++; }
        else if(!strcmp(*argv,"cvam_d")){ cvam_d(); argv++; }
        else if(!strcmp(*argv,"cvexp_d")){ cvexp_d(); argv++; }
        else if(!strcmp(*argv,"cvfill_d")){ cvfill_d(); argv++; }
        else if(!strcmp(*argv,"cvgather_d")){ cvgather_d(); argv++; }
        else if(!strcmp(*argv,"cvjdot_d")){ cvjdot_d(); argv++; }
        else if(!strcmp(*argv,"cvjmul_d")){ cvjmul_d(); argv++; }
        else if(!strcmp(*argv,"cvmag_d")){ cvmag_d(); argv++; }
        else if(!strcmp(*argv,"vcmagsq_d")){ vcmagsq_d(); argv++; }
        else if(!strcmp(*argv,"cvmeansqval_d")){ cvmeansqval_d(); argv++; }
        else if(!strcmp(*argv,"vmaxval_d")){ vmaxval_d(); argv++; }
        else if(!strcmp(*argv,"vminval_d")){ vminval_d(); argv++; }
        else if(!strcmp(*argv,"vsumsqval_d")){ vsumsqval_d(); argv++; }
        else if(!strcmp(*argv,"cvmmul_d")){ cvmmul_d(); argv++; }
        else if(!strcmp(*argv,"rvcmmul_d")){ rvcmmul_d(); argv++; }
        else if(!strcmp(*argv,"cvmprod_d")){ cvmprod_d(); argv++; }
        else if(!strcmp(*argv,"cvmsa_d")){ cvmsa_d(); argv++; }
        else if(!strcmp(*argv,"cvneg_d")){ cvneg_d(); argv++; }
        else if(!strcmp(*argv,"cvouter_d")){ cvouter_d(); argv++; }
        else if(!strcmp(*argv,"cvsam_d")){ cvsam_d(); argv++; }
        else if(!strcmp(*argv,"cvsma_d")){ cvsma_d(); argv++; }
        else if(!strcmp(*argv,"cvswap_d")){ cvswap_d(); argv++; }
        else if(!strcmp(*argv,"gemp_d")){ gemp_d(); argv++; }
        else if(!strcmp(*argv,"gems_d")){ gems_d(); argv++; }
        else if(!strcmp(*argv,"mprod_d")){ mprod_d(); argv++; }
        else if(!strcmp(*argv,"mprodt_d")){ mprodt_d(); argv++; }
        else if(!strcmp(*argv,"mtrans_d")){ mtrans_d(); argv++; }
        else if(!strcmp(*argv,"mvprod_d")){ mvprod_d(); argv++; }
        else if(!strcmp(*argv,"rcvadd_d")){ rcvadd_d(); argv++; }
        else if(!strcmp(*argv,"rcvmul_d")){ rcvmul_d(); argv++; }
        else if(!strcmp(*argv,"rscvmul_d")){ rscvmul_d(); argv++; }
        else if(!strcmp(*argv,"rcvsub_d")){ rcvsub_d(); argv++; }
        else if(!strcmp(*argv,"rscvadd_d")){ rscvadd_d(); argv++; }
        else if(!strcmp(*argv,"svadd_d")){ svadd_d(); argv++; }
        else if(!strcmp(*argv,"svdiv_d")){ svdiv_d(); argv++; }
        else if(!strcmp(*argv,"svmul_d")){ svmul_d(); argv++; }
        else if(!strcmp(*argv,"vadd_d")){ vadd_d(); argv++; }
        else if(!strcmp(*argv,"vsq_d")){ vsq_d(); argv++; }
        else if(!strcmp(*argv,"vsqrt_d")){ vsqrt_d(); argv++; }
        else if(!strcmp(*argv,"cvsqrt_d")){ cvsqrt_d(); argv++; }
        else if(!strcmp(*argv,"vam_d")){ vam_d(); argv++; }
        else if(!strcmp(*argv,"vasin_d")){ vasin_d(); argv++; }
        else if(!strcmp(*argv,"vacos_d")){ vacos_d(); argv++; }
        else if(!strcmp(*argv,"vatan2_d")){ vatan2_d(); argv++; }
        else if(!strcmp(*argv,"vatan_d")){ vatan_d(); argv++; }
        else if(!strcmp(*argv,"vclip_d")){ vclip_d(); argv++; }
        else if(!strcmp(*argv,"vcmaxmgsq_d")){ vcmaxmgsq_d(); argv++; }
        else if(!strcmp(*argv,"vcminmgsqval_d")){ vcminmgsqval_d(); argv++; }
        else if(!strcmp(*argv,"vcmplx_d")){ vcmplx_d(); argv++; }
        else if(!strcmp(*argv,"vdiv_d")){ vdiv_d(); argv++; }
        else if(!strcmp(*argv,"vdot_d")){ vdot_d(); argv++; }
        else if(!strcmp(*argv,"cvdot_d")){ cvdot_d(); argv++; }
        else if(!strcmp(*argv,"veuler_d")){ veuler_d(); argv++; }
        else if(!strcmp(*argv,"vexp_d")){ vexp_d(); argv++; }
        else if(!strcmp(*argv,"vexpoavg_d")){ vexpoavg_d(); argv++; }
        else if(!strcmp(*argv,"cvexpoavg_d")){ cvexpoavg_d(); argv++; }
        else if(!strcmp(*argv,"vfill_d")){ vfill_d(); argv++; }
        else if(!strcmp(*argv,"vgather_d")){ vgather_d(); argv++; }
        else if(!strcmp(*argv,"vhisto_d")){ vhisto_d(); argv++; }
        else if(!strcmp(*argv,"vhypot_d")){ vhypot_d(); argv++; }
        else if(!strcmp(*argv,"vinvclip_d")){ vinvclip_d(); argv++; }
        else if(!strcmp(*argv,"vleq_d")){ vleq_d(); argv++; }
        else if(!strcmp(*argv,"vlne_d")){ vlne_d(); argv++; }
        else if(!strcmp(*argv,"vlgt_d")){ vlgt_d(); argv++; }
        else if(!strcmp(*argv,"vlge_d")){ vlge_d(); argv++; }
        else if(!strcmp(*argv,"vllt_d")){ vllt_d(); argv++; }
        else if(!strcmp(*argv,"vlle_d")){ vlle_d(); argv++; }
        else if(!strcmp(*argv,"vlog_d")){ vlog_d(); argv++; }
        else if(!strcmp(*argv,"vlog10_d")){ vlog10_d(); argv++; }
        else if(!strcmp(*argv,"vmag_d")){ vmag_d(); argv++; }
        else if(!strcmp(*argv,"vmax_d")){ vmax_d(); argv++; }
        else if(!strcmp(*argv,"vmaxmg_d")){ vmaxmg_d(); argv++; }
        else if(!strcmp(*argv,"vmeansqval_d")){ vmeansqval_d(); argv++; }
        else if(!strcmp(*argv,"vmin_d")){ vmin_d(); argv++; }
        else if(!strcmp(*argv,"vminmg_d")){ vminmg_d(); argv++; }
        else if(!strcmp(*argv,"vmmul_d")){ vmmul_d(); argv++; }
        else if(!strcmp(*argv,"vmodulate_d")){ vmodulate_d(); argv++; }
        else if(!strcmp(*argv,"cvmodulate_d")){ cvmodulate_d(); argv++; }
        else if(!strcmp(*argv,"vmprod_d")){ vmprod_d(); argv++; }
        else if(!strcmp(*argv,"vmsa_d")){ vmsa_d(); argv++; }
        else if(!strcmp(*argv,"vouter_d")){ vouter_d(); argv++; }
        else if(!strcmp(*argv,"vpolar_d")){ vpolar_d(); argv++; }
        else if(!strcmp(*argv,"vrect_d")){ vrect_d(); argv++; }
        else if(!strcmp(*argv,"vramp_d")){ vramp_d(); argv++; }
        else if(!strcmp(*argv,"vreal_d")){ vreal_d(); argv++; }
        else if(!strcmp(*argv,"vimag_d")){ vimag_d(); argv++; }
        else if(!strcmp(*argv,"vrecip_d")){ vrecip_d(); argv++; }
        else if(!strcmp(*argv,"vsam_d")){ vsam_d(); argv++; }
        else if(!strcmp(*argv,"vscatter_d")){ vscatter_d(); argv++; }
        else if(!strcmp(*argv,"cvscatter_d")){ cvscatter_d(); argv++; }
        else if(!strcmp(*argv,"vsin_d")){ vsin_d(); argv++; }
        else if(!strcmp(*argv,"vcos_d")){ vcos_d(); argv++; }
        else if(!strcmp(*argv,"vsma_d")){ vsma_d(); argv++; }
        else if(!strcmp(*argv,"vsub_d")){ vsub_d(); argv++; }
        else if(!strcmp(*argv,"vsumval_d")){ vsumval_d(); argv++; }
        else if(!strcmp(*argv,"vtan_d")){ vtan_d(); argv++; }
        else if(!strcmp(*argv,"vneg_d")){ vneg_d(); argv++; }
        else if(!strcmp(*argv,"vmul_d")){ vmul_d(); argv++; }
        else if(!strcmp(*argv,"cvmul_d")){ cvmul_d(); argv++; }
        else if(!strcmp(*argv,"cvdiv_d")){ cvdiv_d(); argv++; }
        else if(!strcmp(*argv,"cvadd_d")){ cvadd_d(); argv++; }
        else if(!strcmp(*argv,"cvsub_d")){ cvsub_d(); argv++; }
        else if(!strcmp(*argv,"csvadd_d")){ csvadd_d(); argv++; }
        else if(!strcmp(*argv,"cvconj_d")){ cvconj_d(); argv++; }
     }    
     vsip_finalize((void*)0);
     return 0;
}
